version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/tomcat7/webapps/sample
    overwrite: yes
  - source: hello.jsp
    destination: /usr/share/tomcat7/webapps/sample
    overwrite: yes
  - source: wared/testJavaApp.war
    destination: /usr/share/tomcat7/webapps/unwared
    overwrite: yes
  - source: jared/testJavaApp.jar
    destination: /usr/share/tomcat7/webapps/unjared
    overwrite: yes
  - source: eared/testJavaApp.ear
    destination: /usr/share/tomcat7/webapps/uneared
    overwrite: yes
  - source: sample/sample.zip
    destination: /usr/share/tomcat7/webapps/unzipped
    overwrite: yes
  - source: META-INF/MANIFEST.MF
    discard-paths: no
    base-directory: META-INF
    destination: /usr/share/tomcat7/webapps/META-INF
    overwrite: yes
  - source: WEB-INF
    discard-paths: no
    base-directory: WEB-INF/web.xml
    destination: /usr/share/tomcat7/webapps/WEB-INF
    overwrite: yes
  - source: WEB-INF
    discard-paths: no
    base-directory: WEB-INF/classes/mypackages/Hello.class
    destination: /usr/share/tomcat7/webapps/WEB-INF
    overwrite: yes
hooks:
  BeforeInstall:

  ApplicationStop:
