version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/tomcat7/webapps/sample
    overwrite: yes
  - source: hello.jsp
    destination: /usr/share/tomcat7/webapps/sample
    overwrite: yes
  - source: wared/testJavaApp.war
    destination: /usr/share/tomcat7/webapps/sample/unwared
    overwrite: yes
  - source: jared/testJavaApp.jar
    destination: /usr/share/tomcat7/webapps/sample/unjared
    overwrite: yes
  - source: eared/testJavaApp.ear
    destination: /usr/share/tomcat7/webapps/sample/uneared
    overwrite: yes
  - source: zipped/sample.zip
    destination: /usr/share/tomcat7/webapps/sample/unzipped
    overwrite: yes
hooks:
  BeforeInstall:

  ApplicationStop:
