version: 0.0
os: linux
files:
  - source: eared/eared.ear
    destination: /usr/share/tomcat7/webapps/uneared
    overwrite: yes
  - source: jared/jared.jar
    destination: /usr/share/tomcat7/webapps/unjared
    overwrite: yes
  - source: wared/wared.war
    destination: /usr/share/tomcat7/webapps/unwared
    overwrite: zipped
  - source: zipped/zipped.zip
    destination: /usr/share/tomcat7/webapps/unzipped
    overwrite: yes
  - source: sample/index.html
    destination: /usr/share/tomcat7/webapps/sample/index.html
    overwrite: yes
  - source: sample/hello.jsp
    destination: /usr/share/tomcat7/webapps/sample/hello.jsp
    overwrite: yes
  - source: sample/buildspec.yml
    destination: /usr/share/tomcat7/webapps/sample/buildspec.yml
    overwrite: yes
  - source: sample/appspec.yml
    destination: /usr/share/tomcat7/webapps/sample/appspec.yml
    overwrite: yes
  - source: sample/appspec.yml
    destination: /usr/share/tomcat7/webapps/sample/appspec.yml
    overwrite: yes
  - source: sample/META-INF/MANIFEST.MF
    destination: /usr/share/tomcat7/webapps/sample/META-INF/MANIFEST.MF
    overwrite: yes
  - source: sample/WEB-INF/web.xml
    destination: /usr/share/tomcat7/webapps/sample/WEB-INF/web.xml
    overwrite: yes
  - source: sample/WEB-INF/classes/mypackage/hello.class
    destination: /usr/share/tomcat7/webapps/sample/WEB-INF/classes/mypackage/hello.class
    overwrite: yes
  - source: appspec.yml
    destination: /usr/share/tomcat7/webapps/appspec.yml
    overwrite: yes
  - source: buildspec.yml
    destination: /usr/share/tomcat7/webapps/buildspec.yml
    overwrite: yes
hooks:
  BeforeInstall:
  ApplicationStop:
