version: 0.0
os: linux
files:
  - source: eared/eared.ear
    destination: /usr/share/tomcat7/webapps/uneared
    overwrite: yes
  - source: jared/jared.jar
    destination: /usr/share/tomcat7/webapps/unjared
    overwrite: yes
  - source: wared/wared.war
    destination: /usr/share/tomcat7/webapps/unwared
    overwrite: yes
  - source: zipped/zipped.zip
    destination: /usr/share/tomcat7/webapps/unzipped
    overwrite: yes
  - source: sample/
    destination: /usr/share/tomcat7/webapps/sample
    overwrite: yes
  - source: appspec.yml
    destination: /usr/share/tomcat7/webapps/appspec.yml
    overwrite: yes
  - source: buildspec.yml
    destination: /usr/share/tomcat7/webapps/buildspec.yml
    overwrite: yes
hooks:
  BeforeInstall:
  ApplicationStop:
